# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moritzbitsch/Repository/Work/commhandler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moritzbitsch/Repository/Work/commhandler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/moritzbitsch/Repository/Work/commhandler && $(CMAKE_COMMAND) -E cmake_progress_start /home/moritzbitsch/Repository/Work/commhandler/CMakeFiles /home/moritzbitsch/Repository/Work/commhandler/lib/coiopp/CMakeFiles/progress.marks
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moritzbitsch/Repository/Work/commhandler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/coiopp/CMakeFiles/coiopp_files.dir/rule:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/CMakeFiles/coiopp_files.dir/rule
.PHONY : lib/coiopp/CMakeFiles/coiopp_files.dir/rule

# Convenience name for target.
coiopp_files: lib/coiopp/CMakeFiles/coiopp_files.dir/rule

.PHONY : coiopp_files

# fast build rule for target.
coiopp_files/fast:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp_files.dir/build.make lib/coiopp/CMakeFiles/coiopp_files.dir/build
.PHONY : coiopp_files/fast

# Convenience name for target.
lib/coiopp/CMakeFiles/coiopp.dir/rule:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f CMakeFiles/Makefile2 lib/coiopp/CMakeFiles/coiopp.dir/rule
.PHONY : lib/coiopp/CMakeFiles/coiopp.dir/rule

# Convenience name for target.
coiopp: lib/coiopp/CMakeFiles/coiopp.dir/rule

.PHONY : coiopp

# fast build rule for target.
coiopp/fast:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/build
.PHONY : coiopp/fast

coio.o: coio.cpp.o

.PHONY : coio.o

# target to build an object file
coio.cpp.o:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio.cpp.o
.PHONY : coio.cpp.o

coio.i: coio.cpp.i

.PHONY : coio.i

# target to preprocess a source file
coio.cpp.i:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio.cpp.i
.PHONY : coio.cpp.i

coio.s: coio.cpp.s

.PHONY : coio.s

# target to generate assembly for a file
coio.cpp.s:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio.cpp.s
.PHONY : coio.cpp.s

coio_glib.o: coio_glib.cpp.o

.PHONY : coio_glib.o

# target to build an object file
coio_glib.cpp.o:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio_glib.cpp.o
.PHONY : coio_glib.cpp.o

coio_glib.i: coio_glib.cpp.i

.PHONY : coio_glib.i

# target to preprocess a source file
coio_glib.cpp.i:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio_glib.cpp.i
.PHONY : coio_glib.cpp.i

coio_glib.s: coio_glib.cpp.s

.PHONY : coio_glib.s

# target to generate assembly for a file
coio_glib.cpp.s:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/coio_glib.cpp.s
.PHONY : coio_glib.cpp.s

libco/libco.o: libco/libco.c.o

.PHONY : libco/libco.o

# target to build an object file
libco/libco.c.o:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/libco/libco.c.o
.PHONY : libco/libco.c.o

libco/libco.i: libco/libco.c.i

.PHONY : libco/libco.i

# target to preprocess a source file
libco/libco.c.i:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/libco/libco.c.i
.PHONY : libco/libco.c.i

libco/libco.s: libco/libco.c.s

.PHONY : libco/libco.s

# target to generate assembly for a file
libco/libco.c.s:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(MAKE) -f lib/coiopp/CMakeFiles/coiopp.dir/build.make lib/coiopp/CMakeFiles/coiopp.dir/libco/libco.c.s
.PHONY : libco/libco.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... coiopp_files"
	@echo "... coiopp"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... coio.o"
	@echo "... coio.i"
	@echo "... coio.s"
	@echo "... coio_glib.o"
	@echo "... coio_glib.i"
	@echo "... coio_glib.s"
	@echo "... libco/libco.o"
	@echo "... libco/libco.i"
	@echo "... libco/libco.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/moritzbitsch/Repository/Work/commhandler && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

